### PR TITLE
Release 2024.4

### PR DESCRIPTION
**Pull request by Waguramu**
**Goal**: combine release 2024.4 PR.

**Includes**:
* Clickable Feature Search markers
* Zoom to feature #7 
* Search history and unified UI #88 #128 
* Keyboard controls #87

### CODE REVIEW

**Comment by josephbirkner** [comment]
This PR also contains (partial?) implementations for picking search results, right?

**Review by josephbirkner — CHANGES_REQUESTED** [review]
Doesn't really work yet. Video from testing with landmarks.ndslive in our mapget-live-cpp test data directory:

Screencast from 2024-08-08 18-40-17.webm

**Comment by Waguramu** [comment]
- [ ] Make sure that Esc closes dialogs correctly in a stackable fashion.
- [ ] Make sure tabbing through elements works consistently.

**Comment by josephbirkner** [comment]
TODOS are here: https://github.com/ndsev/mapviewer/pull/46

**Review by josephbirkner — APPROVED** [review]
This is fine!

**Pull request merged**
